os: linux
dist: focal
group: edge
language: generic
sudo: required
addons:
  apt:
    update:
      - true
services:
  - docker
before_install:
  - | 
    sudo echo '{"registry-mirrors": ["https://ghcr.io"]}' >> /etc/docker/daemon.json
  - sudo systemctl restart docker
script:
  - cd $HOME && git clone https://github.com/spaceskynet/pybluemonday.git && mkdir dist
  - cd $HOME/pybluemonday/
  - sudo docker build . -t=spaceskynet/pybluemonday
  - |
    sudo docker run --user root --rm -i -v "$HOME/dist:/root/dist:rw,z" spaceskynet/pybluemonday bash << EOF
    exit
    EOF
after_success:
  - cd $HOME/dist/
deploy:
  provider: releases
  token: $GitOAUTHToken
  cleanup: false
  file_glob: true
  file: $HOME/dist/*.whl
  on:
    tags: false # Set "true" to deploy only on successful tagged commit builds
    branch: master # Optional: Needs to be exact as the config branch
branches:
  only:
    - master # Set travis builder branch(es) names
  except:
    - /^(?i:untagged)-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
