os: linux
dist: focal
group: edge
language: generic
sudo: required
addons:
  apt:
    update:
      - true
services:
  - docker
before_install:
  - | 
    sudo echo '{"registry-mirrors": ["https://ghcr.io"]}' >> /etc/docker/daemon.json
  - sudo systemctl restart docker
script:
  - cd $HOME && git clone https://github.com/spaceskynet/pybluemonday.git
  - cd $HOME/pybluemonday
  - sudo docker build . -t=spaceskynet/pybluemonday:apline
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 2>/dev/null
  - sudo docker push spaceskynet/pybluemonday:apline
  - cd $HOME && sudo docker run --user root --name=whl_source -d spaceskynet/pybluemonday:apline ping 127.0.0.1
  - sudo docker cp whl_source:/root/dist .
after_success:
  - cd $HOME/pybluemonday
deploy:
  provider: releases
  token: $GitOAUTHToken
  cleanup: false
  file_glob: true
  file: $HOME/dist/*.whl
  on:
    tags: false # Set "true" to deploy only on successful tagged commit builds
    branch: master # Optional: Needs to be exact as the config branch
branches:
  only:
    - master # Set travis builder branch(es) names
  except:
    - /^(?i:untagged)-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
