FROM python:3.10-alpine as py310
RUN sed -e 's/dl-cdn[.]alpinelinux.org/mirrors.aliyun.com/g' -i~ /etc/apk/repositories \
        && apk add --update --no-cache go make clang-dev linux-headers gcc g++ libffi-dev git && \
        rm -rf /var/cache/apk/* && \
        rm -rf /root/.cache/
WORKDIR /root
COPY . /root
RUN python setup.py bdist_wheel

FROM alpine
RUN mkdir -p dist
WORKDIR /root/dist
COPY --from=py310 /root/dist .